feat: Add hover feedback
victorqribeiro/radialMenu pull request #4
Opened 2021-01-28 01:14 UTC by geomod-team

The pull request :
* Adds hover feedback on the radial menu:
  * It possible to change button background color;
  * It possible to change button text color;
  * It possible to add an hover callback funtion. The idea is for example change a CSS variable (see index.html)
* Adds doc generation. To generate api doc from jsDoc, do : `npm run docs`

2021-01-28 01:29 UTC, victorqribeiro commented
you also forgot to update index.html - I changed it to use the build version - build/RadialMenu.min.js

I create this build using `uglifyjs src/RadialMenu.js -c -m -o build/RadialMenu.min.js`

2021-01-28 18:16 UTC, victorqribeiro requested changes

2021-01-28 18:16 UTC, victorqribeiro commented on src/RadialMenu.js
> +export default class RadialMenu {
this is breaking in browser, even if I update the index.html and change to ```<script src="src/RadialMenu.js" type="module"></script>

2021-01-29 01:10 UTC, geomod-team commented on src/RadialMenu.js
> +export default class RadialMenu {
I had `export default` to use esModule. It is just an idea.

To run index.html in local we have to install and run server like [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb).  
Run html file in browser with file:// is not possible with modules [see here](https://medium.com/ghostcoder/using-es6-modules-in-the-browser-5dce9ca9e911)

2021-01-29 01:22 UTC, victorqribeiro commented on src/RadialMenu.js
> +export default class RadialMenu {
yes, I have a server running locally. it was just an lack of update in index.html. Could you please also update style-visualizer.html and the README.md to reflect your changes before I merge?

2021-01-29 01:44 UTC, geomod-team commented on src/RadialMenu.js
> +export default class RadialMenu {
I update style-visualizer.html. 

The README file is up to date. :-) 

I hope that's ok.

2021-01-29 01:56 UTC, merged

2021-01-29 02:00 UTC, victorqribeiro commented
Thank you.

2021-01-29 03:28 UTC, victorqribeiro commented
I think it would be nice if you could add a new style using the features you've add, in the style visualizer. What do you think?